### ISSUE TITLE
人人似乎無法使用了

### ISSUE THREAD

**Issue by NeiL978** [Friday21/auto_sign-python3#1]
我剛剛簽到過 然後我在執行一次 他還是顯示簽到成功
是不是壞了?

**Comment by Friday21** [comment]
人人网现在改变签到策略了， 现在是只要登录进去就默认签到了

**Comment by NeiL978** [comment]
所以還是可以使用嗎？ 我看的不是很懂 @@
還有該怎麼讓他每天固定時間自動簽到呢？

**Comment by Friday21** [comment]
我觉得应该还可以，到登录那一步应该就算签到成功了。 我明天需要再确认一下。 
自动签到我用到的是Ubuntu 的crontab， 我因为有台vps一直在运行，所以把命令添加到那上边就行啦

**Comment by NeiL978** [comment]
那就麻煩您測試看看了，謝謝你
還有就是我有一台macbook 我也照著網路上其他人的教學
設定了crontab 10 0 \* \* \* cd /Users/NeiL_MBP/Documents && python zimuzu.py
請問這樣設定對嗎？ 還有 我需要怎麼做他才會自動執行？我需要一直開著terminal嗎？

**Comment by Friday21** [comment]
现在这个脚本能登陆成功，但不知道为什么不会被记录签到， 还有待研究

**Comment by NeiL978** [comment]
嗯，我使用的時候也是這樣，當我自己登入網頁看時，他是顯示我登入網頁的時間，並非是python簽到的時間

**Comment by Friday21** [comment]
你可以试试我刚刚更新的脚本， 我今天测了可行。

**Comment by NeiL978** [comment]
好 我現在試試看

**Comment by NeiL978** [comment]
看起來是成功了，時間是我使用你的CODE的時間，但他秀出一堆HTML的程式碼，這樣是正確的？

**Comment by Friday21** [comment]
那是我调试时打印出来的数据， 我刚刚更改了代码，最新的不会打印出html字段了

**Comment by NeiL978** [comment]
好的，謝謝你，剛剛執行時，看起來沒什麼問題了，我等晚上12點後，看看他是否會自動簽到了 ＾＾
