### ISSUE TITLE
程式碼在crontab上執行，有編碼的問題

### ISSUE THREAD

**Issue by NeiL978** [Friday21/auto_sign-python3#2]
我的系統是OS X ，當我執行crontab時，log顯示以下的錯誤，看起來像是編碼錯誤的樣子？
看起來像是print不出中文字的樣子 
真不好意思，又麻煩你了

`From ANDY_MBP@ANDYdeMacBook-Pro.local  Thu May 19 04:03:01 2016
Return-Path: ANDY_MBP@ANDYdeMacBook-Pro.local
X-Original-To: ANDY_MBP
Delivered-To: ANDY_MBP@ANDYdeMacBook-Pro.local
Received: by ANDYdeMacBook-Pro.local (Postfix, from userid 501)
    id AB4BD1011734; Thu, 19 May 2016 04:03:01 +0800 (CST)
From: ANDY_MBP@ANDYdeMacBook-Pro.local (Cron Daemon)
To: ANDY_MBP@ANDYdeMacBook-Pro.local
Subject: Cron ANDY_MBP@ANDYdeMacBook-Pro python3 /Users/ANDY_MBP/Documents/crontab/zimuzu.py
X-Cron-Env: <PATH=/Library/Frameworks/Python.framework/Versions/3.5/bin/python3:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <LOGNAME=ANDY_MBP>
X-Cron-Env: <USER=ANDY_MBP>
X-Cron-Env: <HOME=/Users/ANDY_MBP>
Message-Id: 20160518200301.AB4BD101453@ANDYdeMacBook-Pro.local
Date: Thu, 19 May 2016 04:03:01 +0800 (CST)

Traceback (most recent call last):
  File "/Users/ANDY_MBP/Documents/crontab/zimuzu.py", line 83, in <module>
    if sign('123456789@gmail.com', '123456'):
  File "/Users/ANDY_MBP/Documents/crontab/zimuzu.py", line 66, in sign
    print(data['info'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)
`

**Comment by Friday21** [comment]
你把print（data['info']）去掉不打印应该就没问题了，  至于为什么出现这个问题可能跟你的Python 默认编码设置有关，本代码是用Python3 写的， 你的crontab命令crontab 10 0 \* \* \* cd /Users/NeiL_MBP/Documents && python zimuzu.py 则是用Python2 执行， 建议改为crontab 10 0 \* \* \* cd /Users/NeiL_MBP/Documents && python3 zimuzu.py

**Comment by NeiL978** [comment]
我已經改用crontab 10 0 \* \* \* python3 /Users/NeiL_MBP/Documents/crontab/zimuzu.py
所以才跳出編碼問題，之前沒改時，是出現其他lib的錯誤
把66行跟84行改成英文就好了 謝謝你
